MODEL = LARGE
TSLIB = 1
PBLIB = 1

PBLIB_OBJS = pb_lib.obj lang.obj user.obj
AFLAGS	= /o /mx /dMEM_MOD=$(MODEL)

.cpp.obj:
       $(CC) @mc.cfg $(CPPFLAGS) /c $&.cpp
.c.obj:
       $(CC) @mc.cfg $(CFLAGS) /c $&.c

PBLIB_$(EXT).LIB : $(PBLIB_OBJS)
 -erase $@
 &tlib $@ +$?
 
all: PBLIB_$(EXT).LIB
