MODEL = LARGE
EXT   	= L
TSLIB = 1
PBLIB = 1

OBJS = pb_lib.obj lang.obj user.obj
AFLAGS	= /o /mx /dMEM_MOD=$(MODEL)

.cpp.obj:
       $(CC) @mc.cfg $(CPPFLAGS) /c $&.cpp
.c.obj:
       $(CC) @mc.cfg $(CFLAGS) /c $&.c

pblib_$(EXT).lib : $(OBJS)
 -erase $@
 &tlib $@ +$?
 copy $@ $(OUT)
 #-erase $@

$(OBJS) : pb_lib.cpp pb_lib.hpp
