## Makefile for TwinSoftLib 1.xx

MODEL = LARGE

OBJS = date.obj     dirscan.obj  find.obj     dstring.obj  bitarray.obj \
       sound.obj    misc.obj     crc16.obj    crc32.obj    fuzzy.obj    \
       form.obj     msdos.obj    fname.obj    file.obj     inivar.obj   dirfunc.obj  \
       copyfile.obj

TSLIB = 1

tslib_$(EXT).lib: $(OBJS)
 @erase $@
 @$(DIR_BC_BIN)\tlib $@ /c +$(OBJS)
 @copy $@ $(DIR_TSLIB_LIB)
 @erase $@
