
/* ------------------------------------------------------------
 * Filename ............... PbFnames.Hpp
 *
 * General Purpose ........ ProBoard file names
 * ------------------------------------------------------------
 * First date ............. 14 sep 1993
 *
 * First in version ....... 1.40
 *
 * Written by ............. Alain Schellinck
 * ------------------------------------------------------------
 * Revisions:
 * ----------
 *
 *   Date   | By |                  Purpose                   |
 * ---------+----+--------------------------------------------+
 *          |    |                                            |
 *          |    |                                            |
 *          |    |                                            |
 */

/*-------------------------------------------------------------------------*/

#define  fnPbBinLog     "BinLog.Pb"
#define  fnPbConfig     "Config.Pro"
#define  fnPbEvent      "Events.Pro"
#define  fnPbFile       "FileCfg.Pro"
#define  fnPbFileIdx    "FilesIdx.Pb"
#define  fnPbLimits     "Limits.Pro"
#define  fnPbMessage    "MsgAreas.Pb"
#define  fnPbModem      "Modem.Pro"
#define  fnPbOnLine     "Online.Pro"
#define  fnPbProtocol   "Protocol.Pro"
#define  fnPbUsersPb    "UsersPb.Bbs"
#define  fnPbUsersIdx   "UsersIdx.Bbs"
#define  fnPbUsersBbs   "Users.Bbs"
#define  fnPbUsersXi    "UsersXi.Bbs"

/*---------------------------] END OF THE CODE [---------------------------*/
